### ISSUE TITLE
Error Running Quick Start (error 2: out of memory, error 63: OS call failed or operation not supported on this OS)

### ISSUE THREAD

**Issue by bahamakyle** [facebookresearch/deepmask#85]
I am running a MacBook Pro (Retina, Mid 2012) on 10.11.6 with a NVIDIA GeForce GT 650M 1024 MB which is listed as having compute capability 3.0. I start off with this because I see that the DeepMask requirements call for at least 3.5 and this discrepancy may be causing my problems. CUDA 8.0 is installed along with all required Torch packages.

I have gotten the following errors when trying to run the command
`th computeProposals.lua ~/DEEPMASK/pretrained/deepmask`:

Error 1 (this error has only appeared once)

`Found Environment variable CUDNN_PATH = /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.5.dylib	
| loading model file... /Users/Kyle/DEEPMASK/pretrained/deepmask	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-6578/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/Users/Kyle/torch/install/bin/luajit: /Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-6578/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function </Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:245>
	[C]: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	computeProposals.lua:48: in main chunk
	[C]: in function 'dofile'
	...Kyle/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010d8c61c0`

Error 2 (this error has appeared on every other try)

`Found Environment variable CUDNN_PATH = /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.5.dylib	
| loading model file... /Users/Kyle/DEEPMASK/pretrained/deepmask	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-6578/cutorch/lib/THC/generic/THCStorage.cu line=66 error=63 : OS call failed or operation not supported on this OS
/Users/Kyle/torch/install/bin/luajit: /Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: cuda runtime error (63) : OS call failed or operation not supported on this OS at /tmp/luarocks_cutorch-scm-1-6578/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function </Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:245>
	[C]: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/Kyle/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	computeProposals.lua:48: in main chunk
	[C]: in function 'dofile'
	...Kyle/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x01082971c0`

Does anyone know why I would receive these errors? Is it due to my compute capability being 3.0? Thanks very much for your help as I have found it difficult to figure out where to begin with debugging the issue.

**Comment by Tengke-Xiong** [comment]
I have the same errors, my Mac with a NVIDIA GeForce GT 750M 2048 MB

**Comment by osfa** [comment]
I resolved this by upgrading from OSX 10.11 to 10.12.
