### ISSUE TITLE
Error when running computeProposals.lua on own model

### ISSUE THREAD

**Issue by ryanfb** [facebookresearch/deepmask#9]
I'm interested in experimenting with training DeepMask/SharpMask against my own data, so as a first pass I'm following the instructions for training your own model against the COCO images and annotations.

When I run `th computeProposals.lua` against the resulting model directory, I get this error:

```
| loading model file... /Users/ryan/mess/current/deepmask/exps/deepmask/exp,batch=8,maxepoch=10
| start
/Users/ryan/source/torch/install/bin/luajit: bad argument #2 to '?' (out of range at /Users/ryan/source/torch/pkg/torch/generic/Tensor.c:890)
stack traceback:
        [C]: at 0x0b5e7600
        [C]: in function '__index'
        /Users/ryan/mess/2016/34/deepmask/InferDeepMask.lua:167: in function 'getTopScores'
        /Users/ryan/mess/2016/34/deepmask/InferDeepMask.lua:224: in function 'getTopProps'
        computeProposals.lua:84: in main chunk
        [C]: in function 'dofile'
        ...urce/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x010b2a3cf0
```

I had to reduce the batch size to 8 to get `train.lua` to run on my GPU without a CUDA out of memory error, and I've tried multiple other tweaks and re-trainings with this batch size to see if something else would produce a training file that worked (I initially tried maxload 1000 with the default of 300 epochs, which is what initially produced this error).

`evalPerPatch.lua` runs fine against these custom models, `evalPerImage.lua` gives a similar error.

Running against the pre-trained DeepMask/SharpMask models also works fine.

**Comment by poliveirap** [comment]
Hi, thanks for pointing this out.
Indeed there was a problem. Basically because of BNtoFixed() function in modelUtils.lua, which was old (I think the batchnorm module has been modified and that was causing the trouble).
As per @szagoruyko 's previous advice, I update the modelUtils.lua to use the functions from inn package :) (therefore now it will require installation of this package -- 'luarocks install inn' should do it).

So actually, the way it was, the weights were exploding and the model was outputing 'nan' and causing problem during inference. (the problem is not due to the fact that you were using a smaller batch size).

I pushed a new version that is now working (training, evalPerPatch, evalPerImage and computeProposals) here in my side. 

Can you check if it works for you as well (dont forget to install 'inn')?

Thanks for pointing out again :).

**Comment by ryanfb** [comment]
Thank! I ran a short training after updating DeepMask and installing `inn` (after which it no longer showed `nan` for loss during training), and `computeProposals.lua` now works against the resulting custom DeepMask model.
